name: Terrascan Scan

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terrascan
      run: |
        curl -L https://github.com/accurics/terrascan/releases/latest/download/terrascan_${{ runner.os }}_amd64 -o terrascan
        chmod +x terrascan
        sudo mv terrascan /usr/local/bin/

    - name: Display Terrascan Script
      run: |
        cat /usr/local/bin/terrascan

    - name: Run Terrascan
      run: |
        cd charts/hello-world
        terrascan scan -i terraform
